#!/bin/bash
# One-shot registration (or removal) of ALL PEAM analyses in a TraceCompass
# workspace — replaces clicking through "Add External Analysis..." and
# "Manage XML analyses... > Import" (or the corresponding removals) one by one.
#
#   usage: ./tc-setup.sh [--remove] [--workspace DIR]
#     (no flag)      install/refresh all PEAM analyses (default)
#     --remove, -r   remove every PEAM analysis this script installs
#     --workspace    override TC_WORKSPACE (else config/defaults)
#     --help, -h     show this help
#
# RUN WITH TRACECOMPASS CLOSED: TC reads these locations at startup and
# caches state; changes made while it runs may be ignored or overwritten.
#
# What it installs / removes (paths confirmed against TC source,
# LamiConfigUtils.java and XmlUtils.java):
#   1. External (LAMI) analyses — one .properties file (keys: name, command)
#      per analysis under
#      .metadata/.plugins/org.eclipse.tracecompass.analysis.lami.core/user-defined-configs/
#      pointing at the committed lami_<analysis>.sh wrappers in this folder.
#   2. XML data-driven analyses — copies this folder's *.xml into
#      .metadata/.plugins/org.eclipse.tracecompass.tmf.analysis.xml.core/xml_files/
#
# Idempotent both ways: install overwrites existing PEAM entries with current
# ones; --remove deletes every PEAM LAMI entry (identified by the marker line
# this script writes, so stale/renamed entries are cleaned too) and every XML
# in the workspace whose name matches one this folder ships.

MODE="install"
WS_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --remove|-r|--uninstall) MODE="remove" ;;
    --workspace) shift; WS_OVERRIDE="$1" ;;
    --workspace=*) WS_OVERRIDE="${1#*=}" ;;
    --help|-h)
      sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *)
      echo "error: unknown argument '$1' (see --help)" >&2; exit 2 ;;
  esac
  shift
done

. "$(dirname "$0")/tc-common.sh" 2>/dev/null || {
  # tc-common.sh ends by defining functions only; sourcing must not exec.
  echo "error: cannot source tc-common.sh" >&2; exit 1
}

WS="${WS_OVERRIDE:-$TC_WORKSPACE}"
if [ ! -d "$WS/.metadata" ]; then
  echo "error: '$WS' does not look like an Eclipse workspace (no .metadata)." >&2
  echo "Set TC_WORKSPACE in tc-local.conf (see tc-local.conf.example)," >&2
  echo "or pass --workspace DIR." >&2
  exit 1
fi

LAMI_DIR="$WS/.metadata/.plugins/org.eclipse.tracecompass.analysis.lami.core/user-defined-configs"
XML_DIR="$WS/.metadata/.plugins/org.eclipse.tracecompass.tmf.analysis.xml.core/xml_files"

# Marker line written into every PEAM-generated LAMI .properties; --remove
# uses it to find PEAM entries (catches renamed/stale ones the current run
# would no longer register).
PEAM_MARKER="generated by tc-setup.sh"

if [ "$MODE" = "remove" ]; then
  # ---- 1. external (LAMI) analyses -- remove PEAM-marked .properties -------
  removed=0
  if [ -d "$LAMI_DIR" ]; then
    for f in "$LAMI_DIR"/*.properties; do
      [ -f "$f" ] || continue
      if grep -q "$PEAM_MARKER" "$f" 2>/dev/null; then
        rm -f "$f" && { echo "removed external analysis: $(basename "$f")"; removed=$((removed+1)); }
      fi
    done
  fi
  [ "$removed" -eq 0 ] && echo "no PEAM external analyses found in workspace"

  # ---- 2. XML data-driven analyses -- remove ones this folder ships --------
  removed=0
  for x in "$TC_HERE"/*.xml; do
    [ -f "$x" ] || continue
    target="$XML_DIR/$(basename "$x")"
    if [ -f "$target" ]; then
      rm -f "$target" && { echo "removed XML analysis: $(basename "$x")"; removed=$((removed+1)); }
    fi
  done
  [ "$removed" -eq 0 ] && echo "no PEAM XML analyses found in workspace"

  echo
  echo "Done. Restart TraceCompass to drop the removed analyses. Workspace: $WS"
  exit 0
fi

mkdir -p "$LAMI_DIR" "$XML_DIR"

# ---- 1. external (LAMI) analyses -----------------------------------------
register() {  # register <analysis_module> <display name>
  local mod="$1" disp="$2"
  local wrapper="$TC_HERE/lami_${mod}.sh"
  if [ ! -x "$wrapper" ]; then
    echo "skip: $wrapper not found/executable" >&2; return
  fi
  local f="$LAMI_DIR/pinsight_${mod}.properties"
  {
    echo "# PEAM external analysis ($PEAM_MARKER; safe to delete)"
    echo "name=$disp"
    echo "command=$wrapper"
  } > "$f"
  echo "registered external analysis: $disp"
}

register load_imbalance   "PInsight load imbalance"
register mpi_latency      "PInsight MPI latency"
register gpu_datamovement "PInsight GPU data movement"
register halo_exchange    "PInsight halo exchange"

# ---- 2. XML data-driven analyses -----------------------------------------
# The XML analyses live in this same folder (src/tc/) since the 2026-07-20
# restructure.
for x in "$TC_HERE"/*.xml; do
  [ -f "$x" ] || continue
  cp "$x" "$XML_DIR/"
  echo "installed XML analysis: $(basename "$x")"
done

echo
echo "Done. Start TraceCompass; the analyses appear under External Analyses"
echo "and apply to traces automatically (XML). Workspace: $WS"
